# secretstore-tailscale.yaml
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: tailscale-store
  namespace: tailscale
spec:
  provider:
    gcpsm:
      projectID: ${PROJECT_ID_V2}
